# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - test-automation

#image: marketsquare/robotframework-browser

run-automation:       # This job runs in the build stage, which runs first.
  stage: test-automation
  variables:
    TEST_USER: $TEST_USER
    TEST_PASSWORD: $TEST_PASSWORD
  before_script:
    - apt-get update
    - apt-get install -y default-jdk
    - apt-get install -y xvfb
    - apt-get install -y zip
    - apt-get install -y python-is-python3
    - apt-get install -y python3-pip
    - apt-get install -y libnss3-dev libasound2 libxss1 libappindicator3-1 gconf-service libgconf-2-4 libxkbcommon0 libvulkan1 libu2f-udev libpango1.0-0 xdg-utils fonts-liberation libgbm1 libcurl3-gnutls libcurl3-nss libcurl4 libgtk-4-1
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - dpkg -i google-chrome*.deb
    - rm google-chrome*.deb
    - wget -N https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.55/linux64/chromedriver-linux64.zip
    - unzip chromedriver-linux64.zip
    - cd chromedriver-linux64/
    - chmod +x chromedriver
    - cp chromedriver /usr/local/bin
    - cd ..
  script:
    - pip3 install -r ./config/requirements.txt --break-system-packages
    - robot --pythonpath . --outputdir ./allure-report ./tests/demo_planittesting.robot

  artifacts:
    when: always
    paths:
      - ./allure-report/
    expire_in: 1 week
